/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.PersonProfile;

/**
 *
 * @author Admin
 */
public class PersonProfileJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PersonProfileJPanel
     */
   PersonProfile personprofile;
   PersonProfile pp; 
   
   
    public PersonProfileJPanel(PersonProfile personprofile) {
        initComponents();
        
        this.personprofile = personprofile;
         this.personprofile = pp;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblpersoninfo = new javax.swing.JLabel();
        tabpaneperson = new javax.swing.JTabbedPane();
        PnlEdit = new javax.swing.JPanel();
        lblfirstname = new javax.swing.JLabel();
        txtfirstname = new javax.swing.JTextField();
        lblmiddlename = new javax.swing.JLabel();
        txtmiddlename = new javax.swing.JTextField();
        lbllastname = new javax.swing.JLabel();
        txtlastname = new javax.swing.JTextField();
        lblneuid = new javax.swing.JLabel();
        txtneuid = new javax.swing.JTextField();
        passwordchange = new javax.swing.JPasswordField();
        lblchangepassword = new javax.swing.JLabel();
        lblconfirmpassword = new javax.swing.JLabel();
        passwordconfirm = new javax.swing.JPasswordField();
        lblemail = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        txtbirthdate = new javax.swing.JTextField();
        lblbirthdate = new javax.swing.JLabel();
        lbladdress = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        btnupdate = new javax.swing.JButton();
        Pnlview = new javax.swing.JPanel();
        lblfirstname1 = new javax.swing.JLabel();
        txtfirstname1 = new javax.swing.JTextField();
        lblmiddlename1 = new javax.swing.JLabel();
        txtmiddlename1 = new javax.swing.JTextField();
        lbllastname1 = new javax.swing.JLabel();
        txtlastname1 = new javax.swing.JTextField();
        lblneuid1 = new javax.swing.JLabel();
        txtneuid1 = new javax.swing.JTextField();
        lblemail1 = new javax.swing.JLabel();
        txtemail1 = new javax.swing.JTextField();
        lblbirthdate1 = new javax.swing.JLabel();
        txtbirthdate1 = new javax.swing.JTextField();
        lbladdress1 = new javax.swing.JLabel();
        txtaddress1 = new javax.swing.JTextField();
        btnlogout = new javax.swing.JButton();

        lblpersoninfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpersoninfo.setText("Person Information");

        tabpaneperson.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblfirstname.setText("First Name:");

        lblmiddlename.setText("Middle Name:");

        lbllastname.setText("Last Name: ");

        txtlastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlastnameActionPerformed(evt);
            }
        });

        lblneuid.setText("NEU ID:");

        lblchangepassword.setText("Change Password:");

        lblconfirmpassword.setText("Confirm Password:");

        lblemail.setText("Email ID:");

        txtbirthdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbirthdateActionPerformed(evt);
            }
        });

        lblbirthdate.setText("Date of Birth:");

        lbladdress.setText("Address:");

        btnupdate.setText("Update");

        javax.swing.GroupLayout PnlEditLayout = new javax.swing.GroupLayout(PnlEdit);
        PnlEdit.setLayout(PnlEditLayout);
        PnlEditLayout.setHorizontalGroup(
            PnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblchangepassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PnlEditLayout.createSequentialGroup()
                .addComponent(lblconfirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlEditLayout.createSequentialGroup()
                .addGroup(PnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PnlEditLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlEditLayout.createSequentialGroup()
                                .addGroup(PnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblfirstname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblmiddlename, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                    .addComponent(lbllastname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(PnlEditLayout.createSequentialGroup()
                                .addComponent(lblneuid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(31, 31, 31)))
                        .addGroup(PnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtfirstname, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(txtneuid)
                            .addComponent(txtmiddlename)
                            .addComponent(txtlastname)
                            .addComponent(passwordchange)
                            .addComponent(passwordconfirm)))
                    .addGroup(PnlEditLayout.createSequentialGroup()
                        .addGroup(PnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlEditLayout.createSequentialGroup()
                                .addGroup(PnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblbirthdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE))
                            .addGroup(PnlEditLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbladdress, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)))
                        .addGroup(PnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnupdate)
                            .addGroup(PnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtemail, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                .addComponent(txtbirthdate)
                                .addComponent(txtaddress)))))
                .addGap(187, 187, 187))
        );
        PnlEditLayout.setVerticalGroup(
            PnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlEditLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfirstname)
                    .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmiddlename)
                    .addComponent(txtmiddlename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllastname)
                    .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblneuid)
                    .addComponent(txtneuid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblchangepassword)
                    .addComponent(passwordchange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblconfirmpassword)
                    .addComponent(passwordconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblemail)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbirthdate)
                    .addComponent(txtbirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbladdress)
                    .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnupdate)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        tabpaneperson.addTab("Edit", PnlEdit);

        lblfirstname1.setText("First Name:");

        lblmiddlename1.setText("Middle Name:");

        lbllastname1.setText("Last Name: ");

        txtlastname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlastname1ActionPerformed(evt);
            }
        });

        lblneuid1.setText("NEU ID:");

        lblemail1.setText("Email ID:");

        lblbirthdate1.setText("Date of Birth:");

        txtbirthdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbirthdate1ActionPerformed(evt);
            }
        });

        lbladdress1.setText("Address:");

        javax.swing.GroupLayout PnlviewLayout = new javax.swing.GroupLayout(Pnlview);
        Pnlview.setLayout(PnlviewLayout);
        PnlviewLayout.setHorizontalGroup(
            PnlviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlviewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlviewLayout.createSequentialGroup()
                        .addGroup(PnlviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlviewLayout.createSequentialGroup()
                                .addGroup(PnlviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblfirstname1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblmiddlename1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbllastname1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE))
                            .addGroup(PnlviewLayout.createSequentialGroup()
                                .addComponent(lblneuid1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(31, 31, 31)))
                        .addGroup(PnlviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtfirstname1)
                            .addComponent(txtneuid1)
                            .addComponent(txtmiddlename1)
                            .addComponent(txtlastname1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PnlviewLayout.createSequentialGroup()
                        .addGroup(PnlviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblbirthdate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblemail1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PnlviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtemail1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbirthdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PnlviewLayout.createSequentialGroup()
                        .addComponent(lbladdress1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtaddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(187, 187, 187))
        );
        PnlviewLayout.setVerticalGroup(
            PnlviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlviewLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PnlviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfirstname1)
                    .addComponent(txtfirstname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmiddlename1)
                    .addComponent(txtmiddlename1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllastname1)
                    .addComponent(txtlastname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblneuid1)
                    .addComponent(txtneuid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblemail1)
                    .addComponent(txtemail1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblbirthdate1)
                    .addComponent(txtbirthdate1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbladdress1)
                    .addComponent(txtaddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(238, Short.MAX_VALUE))
        );

        tabpaneperson.addTab("View", Pnlview);

        btnlogout.setText("Logout");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnlogout)
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblpersoninfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tabpaneperson)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblpersoninfo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnlogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabpaneperson, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtlastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlastnameActionPerformed

    private void txtbirthdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbirthdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbirthdateActionPerformed

    private void txtlastname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlastname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlastname1ActionPerformed

    private void txtbirthdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbirthdate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbirthdate1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlEdit;
    private javax.swing.JPanel Pnlview;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel lbladdress;
    private javax.swing.JLabel lbladdress1;
    private javax.swing.JLabel lblbirthdate;
    private javax.swing.JLabel lblbirthdate1;
    private javax.swing.JLabel lblchangepassword;
    private javax.swing.JLabel lblconfirmpassword;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblemail1;
    private javax.swing.JLabel lblfirstname;
    private javax.swing.JLabel lblfirstname1;
    private javax.swing.JLabel lbllastname;
    private javax.swing.JLabel lbllastname1;
    private javax.swing.JLabel lblmiddlename;
    private javax.swing.JLabel lblmiddlename1;
    private javax.swing.JLabel lblneuid;
    private javax.swing.JLabel lblneuid1;
    private javax.swing.JLabel lblpersoninfo;
    private javax.swing.JPasswordField passwordchange;
    private javax.swing.JPasswordField passwordconfirm;
    private javax.swing.JTabbedPane tabpaneperson;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtaddress1;
    private javax.swing.JTextField txtbirthdate;
    private javax.swing.JTextField txtbirthdate1;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtemail1;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtfirstname1;
    private javax.swing.JTextField txtlastname;
    private javax.swing.JTextField txtlastname1;
    private javax.swing.JTextField txtmiddlename;
    private javax.swing.JTextField txtmiddlename1;
    private javax.swing.JTextField txtneuid;
    private javax.swing.JTextField txtneuid1;
    // End of variables declaration//GEN-END:variables
}
